name: info_toast
description: A package to help you seamlessly create beautiful and customizable animated toasts and alerts in your app.
version: 1.0.0
homepage: 'https://github.com/theadeyemiolayinka/info_toast'
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter: null